#!/usr/bin/env python3
"""Generate disposable Conceptarium projections.

The Concept Registry is authoritative for predicate presence.
Canonical Markdown entries remain authoritative for full semantic content.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
import json
from pathlib import Path
import re
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
ENTRIES = ROOT / "entries"
REGISTRY = ROOT / "registry" / "concepts.yml"
DEFAULT_OUTPUT = ROOT / "build"


def read_entry(path: Path) -> tuple[dict[str, Any], str]:
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing opening frontmatter delimiter")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration as exc:
        raise ValueError(f"{path}: missing closing frontmatter delimiter") from exc

    meta = yaml.safe_load("\n".join(lines[1:end]))
    if not isinstance(meta, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    body = "\n".join(lines[end + 1 :]).strip()
    return meta, body


def section(body: str, heading: str) -> str | None:
    pattern = re.compile(
        rf"^## {re.escape(heading)}\s*$\n(?P<body>.*?)(?=^##\s|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(body)
    if not match:
        return None
    value = match.group("body").strip()
    return value or None


def load_registry() -> list[dict[str, Any]]:
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not isinstance(data.get("concepts"), list):
        raise ValueError("registry/concepts.yml must contain a top-level concepts list")
    return [x for x in data["concepts"] if isinstance(x, dict)]


def load_entries() -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for path in sorted(ENTRIES.glob("*.md")):
        if path.name == "_template.md":
            continue
        meta, body = read_entry(path)
        result.append(
            {
                "path": path.relative_to(ROOT).as_posix(),
                "meta": meta,
                "body": body,
                "problem_pressure": section(body, "Problem pressure"),
                "open_questions": section(body, "Open questions"),
            }
        )
    return result


def write_dictionary(entries: list[dict[str, Any]], output: Path) -> None:
    rows = sorted(entries, key=lambda e: str(e["meta"]["term"]).casefold())
    lines = [
        "# Conceptarium — Dictionary Projection",
        "",
        "> Generated from materialized canonical entries. Do not edit this file directly.",
        "",
    ]
    for entry in rows:
        meta = entry["meta"]
        lines += [f"## {meta['term']}", "", str(meta["gloss"]).strip(), ""]

        details = [
            f"**Type:** {meta.get('type', 'unknown')}",
            f"**Status:** {meta.get('status', 'unknown')}",
        ]
        domains = meta.get("domains") or []
        if domains:
            details.append("**Domains:** " + ", ".join(map(str, domains)))
        aliases = meta.get("aliases") or []
        if aliases:
            details.append("**Aliases:** " + ", ".join(map(str, aliases)))
        details.append(f"**Canonical source:** `{entry['path']}`")
        lines += details + [""]

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_graph(
    entries: list[dict[str, Any]],
    registry: list[dict[str, Any]],
    output: Path,
) -> None:
    by_entry = {str(e["meta"]["id"]): e for e in entries}
    by_registry = {str(r["id"]): r for r in registry}
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []

    for concept_id, record in sorted(by_registry.items()):
        entry = by_entry.get(concept_id)
        if entry is not None:
            meta = entry["meta"]
            node = {
                "id": concept_id,
                "term": meta.get("term"),
                "materialization": "entry",
                "ontology_state": record.get("ontology_state"),
                "type": meta.get("type"),
                "status": meta.get("status"),
                "gloss": meta.get("gloss"),
                "domains": meta.get("domains") or [],
                "aliases": meta.get("aliases") or [],
                "origin": meta.get("origin") or {},
                "source": entry["path"],
            }
        else:
            node = {
                "id": concept_id,
                "term": record.get("term"),
                "materialization": "registry-only",
                "ontology_state": record.get("ontology_state"),
                "type": None,
                "status": None,
                "gloss": None,
                "domains": [],
                "aliases": [],
                "origin": {},
                "source": None,
                "queue_group": record.get("queue_group"),
                "capture": record.get("capture") or {},
            }
        nodes.append(node)

    for entry in entries:
        meta = entry["meta"]
        source_id = str(meta["id"])
        for relation in meta.get("relations") or []:
            if not isinstance(relation, dict):
                continue
            target = relation.get("target")
            rel_type = relation.get("type")
            if not isinstance(target, str) or not isinstance(rel_type, str):
                continue
            target_record = by_registry.get(target)
            edges.append(
                {
                    "source": source_id,
                    "type": rel_type,
                    "target": target,
                    "target_registered": target_record is not None,
                    "target_materialization": (
                        target_record.get("materialization") if target_record else None
                    ),
                }
            )

    payload = {
        "generated_from": ["registry/concepts.yml", "entries/*.md"],
        "registered_concept_count": len(nodes),
        "materialized_entry_count": len(entries),
        "edge_count": len(edges),
        "nodes": nodes,
        "edges": sorted(edges, key=lambda e: (e["source"], e["type"], e["target"])),
    }
    output.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, default=str) + "\n",
        encoding="utf-8",
    )


def write_frontier(
    entries: list[dict[str, Any]],
    registry: list[dict[str, Any]],
    output: Path,
) -> None:
    rows = sorted(entries, key=lambda e: str(e["meta"]["term"]).casefold())
    queue = sorted(
        [r for r in registry if r.get("materialization") == "registry-only"],
        key=lambda r: str(r.get("term", "")).casefold(),
    )
    lines = [
        "# Conceptarium — Research Frontier",
        "",
        "> Generated from registry presence, entry statuses, and `Open questions` sections.",
        "",
        "## Registered concepts awaiting materialization",
        "",
    ]
    if queue:
        for item in queue:
            group = item.get("queue_group")
            suffix = f" — {group}" if group else ""
            lines.append(f"- **{item.get('term')}** (`{item.get('id')}`){suffix}")
    else:
        lines.append("_No registry-only concepts._")
    lines += ["", "## Entries explicitly under development", ""]

    unresolved = [
        e for e in rows if e["meta"].get("status") in {"seed", "provisional", "contested"}
    ]
    if unresolved:
        for entry in unresolved:
            meta = entry["meta"]
            lines.append(
                f"- **{meta['term']}** — {meta.get('status')}: {meta.get('gloss', '')}"
            )
    else:
        lines.append("_None currently marked seed, provisional, or contested._")
    lines += ["", "## Open questions by concept", ""]

    for entry in rows:
        questions = entry["open_questions"]
        if not questions:
            continue
        lines += [
            f"### {entry['meta']['term']}",
            "",
            questions,
            "",
            f"_Source: `{entry['path']}`_",
            "",
        ]

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_problem_pressure(entries: list[dict[str, Any]], output: Path) -> None:
    rows = sorted(entries, key=lambda e: str(e["meta"]["term"]).casefold())
    lines = [
        "# Conceptarium — Problem-Pressure Index",
        "",
        "> Reverse index from the frustration, anomaly, contradiction, or unfinished thought",
        "> that made a concept necessary. Generated from canonical `Problem pressure` sections.",
        "",
        "Use this projection when you remember **the problem** but have forgotten the word.",
        "",
    ]
    for entry in rows:
        pressure = entry["problem_pressure"]
        if not pressure:
            continue
        lines += [
            f"## {entry['meta']['term']}",
            "",
            pressure,
            "",
            f"_Canonical entry: `{entry['path']}`_",
            "",
        ]
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_promotion_queue(registry: list[dict[str, Any]], output: Path) -> None:
    groups: defaultdict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in registry:
        if item.get("materialization") != "registry-only":
            continue
        groups[str(item.get("queue_group") or "Ungrouped")].append(item)

    total = sum(len(items) for items in groups.values())
    lines = [
        "# Conceptarium — Promotion Queue",
        "",
        "> Generated from registry-only concepts in `registry/concepts.yml`.",
        "> Predicate presence is already durable; promotion means semantic materialization can happen later.",
        "",
        f"**{total} registered concept(s) awaiting full materialization.**",
        "",
    ]

    for group in sorted(groups, key=str.casefold):
        lines += [f"## {group}", ""]
        for item in sorted(groups[group], key=lambda x: str(x.get("term", "")).casefold()):
            lines.append(f"### {item.get('term')}")
            lines.append("")
            lines.append(f"- **ID:** `{item.get('id')}`")
            lines.append(f"- **Ontology state:** {item.get('ontology_state', 'unknown')}")
            note = (item.get("capture") or {}).get("note")
            context = (item.get("capture") or {}).get("context")
            if note:
                lines.append(f"- **Capture note:** {note}")
            if context:
                lines.append(f"- **Context:** {context}")
            lines.append("")

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_registry_json(registry: list[dict[str, Any]], output: Path) -> None:
    output.write_text(
        json.dumps(
            sorted(registry, key=lambda r: str(r.get("id", ""))),
            indent=2,
            ensure_ascii=False,
            default=str,
        )
        + "\n",
        encoding="utf-8",
    )


def write_catalog(
    entries: list[dict[str, Any]],
    registry: list[dict[str, Any]],
    output: Path,
) -> None:
    by_entry = {str(e["meta"]["id"]): e for e in entries}
    payload: list[dict[str, Any]] = []

    for record in sorted(registry, key=lambda r: str(r.get("id", ""))):
        concept_id = str(record.get("id"))
        entry = by_entry.get(concept_id)
        if entry is None:
            payload.append(
                {
                    "id": concept_id,
                    "term": record.get("term"),
                    "presence": record.get("presence"),
                    "materialization": "registry-only",
                    "ontology_state": record.get("ontology_state"),
                    "queue_group": record.get("queue_group"),
                    "capture": record.get("capture") or {},
                    "source": None,
                }
            )
            continue

        meta = entry["meta"]
        payload.append(
            {
                "id": meta.get("id"),
                "term": meta.get("term"),
                "presence": "registered",
                "materialization": "entry",
                "ontology_state": record.get("ontology_state"),
                "type": meta.get("type"),
                "status": meta.get("status"),
                "gloss": meta.get("gloss"),
                "domains": meta.get("domains") or [],
                "aliases": meta.get("aliases") or [],
                "origin": meta.get("origin") or {},
                "relations": meta.get("relations") or [],
                "source": entry["path"],
            }
        )

    output.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, default=str) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="directory for disposable generated projections",
    )
    args = parser.parse_args()

    registry = load_registry()
    entries = load_entries()
    output = args.output_dir
    output.mkdir(parents=True, exist_ok=True)

    write_dictionary(entries, output / "dictionary.md")
    write_graph(entries, registry, output / "graph.json")
    write_frontier(entries, registry, output / "frontier.md")
    write_problem_pressure(entries, output / "problem-pressure.md")
    write_promotion_queue(registry, output / "promotion-queue.md")
    write_registry_json(registry, output / "registry.json")
    write_catalog(entries, registry, output / "catalog.json")

    registry_only = sum(1 for r in registry if r.get("materialization") == "registry-only")
    print(
        f"Generated 7 projections from {len(registry)} registered concepts "
        f"({len(entries)} materialized, {registry_only} registry-only) in {output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
