#!/usr/bin/env python3
"""Generate derived Conceptarium views from canonical entries.

Generated files are disposable projections. The Markdown/YAML entries remain
authoritative.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
ENTRIES = ROOT / "entries"
DEFAULT_OUTPUT = ROOT / "build"


def read_entry(path: Path) -> tuple[dict[str, Any], str]:
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing opening frontmatter delimiter")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration as exc:
        raise ValueError(f"{path}: missing closing frontmatter delimiter") from exc

    meta = yaml.safe_load("\n".join(lines[1:end]))
    if not isinstance(meta, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    body = "\n".join(lines[end + 1 :]).strip()
    return meta, body


def section(body: str, heading: str) -> str | None:
    """Extract a level-2 Markdown section without requiring a Markdown parser."""
    pattern = re.compile(
        rf"^## {re.escape(heading)}\s*$\n(?P<body>.*?)(?=^##\s|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(body)
    if not match:
        return None
    value = match.group("body").strip()
    return value or None


def load_entries() -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for path in sorted(ENTRIES.glob("*.md")):
        if path.name == "_template.md":
            continue
        meta, body = read_entry(path)
        result.append(
            {
                "path": path.relative_to(ROOT).as_posix(),
                "meta": meta,
                "body": body,
                "problem_pressure": section(body, "Problem pressure"),
                "open_questions": section(body, "Open questions"),
            }
        )
    return result


def write_dictionary(entries: list[dict[str, Any]], output: Path) -> None:
    rows = sorted(entries, key=lambda e: str(e["meta"]["term"]).casefold())
    lines = [
        "# Conceptarium — Dictionary Projection",
        "",
        "> Generated from canonical entries. Do not edit this file directly.",
        "",
    ]
    for entry in rows:
        meta = entry["meta"]
        lines += [f"## {meta['term']}", "", str(meta["gloss"]).strip(), ""]

        details: list[str] = []
        details.append(f"**Type:** {meta.get('type', 'unknown')}")
        details.append(f"**Status:** {meta.get('status', 'unknown')}")

        domains = meta.get("domains") or []
        if domains:
            details.append("**Domains:** " + ", ".join(map(str, domains)))

        aliases = meta.get("aliases") or []
        if aliases:
            details.append("**Aliases:** " + ", ".join(map(str, aliases)))

        details.append(f"**Canonical source:** `{entry['path']}`")
        lines += details + [""]

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_graph(entries: list[dict[str, Any]], output: Path) -> None:
    ids = {str(e["meta"]["id"]) for e in entries}
    nodes = []
    edges = []

    for entry in entries:
        meta = entry["meta"]
        node_id = str(meta["id"])
        nodes.append(
            {
                "id": node_id,
                "term": meta.get("term"),
                "type": meta.get("type"),
                "status": meta.get("status"),
                "gloss": meta.get("gloss"),
                "domains": meta.get("domains") or [],
                "aliases": meta.get("aliases") or [],
                "origin": meta.get("origin") or {},
                "source": entry["path"],
            }
        )

        for relation in meta.get("relations") or []:
            if not isinstance(relation, dict):
                continue
            target = relation.get("target")
            rel_type = relation.get("type")
            if not isinstance(target, str) or not isinstance(rel_type, str):
                continue
            edges.append(
                {
                    "source": node_id,
                    "type": rel_type,
                    "target": target,
                    "target_exists": target in ids,
                }
            )

    payload = {
        "generated_from": "entries/*.md",
        "node_count": len(nodes),
        "edge_count": len(edges),
        "nodes": sorted(nodes, key=lambda n: n["id"]),
        "edges": sorted(edges, key=lambda e: (e["source"], e["type"], e["target"])),
    }
    output.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def write_frontier(entries: list[dict[str, Any]], output: Path) -> None:
    rows = sorted(entries, key=lambda e: str(e["meta"]["term"]).casefold())
    lines = [
        "# Conceptarium — Research Frontier",
        "",
        "> Generated from entry statuses and `Open questions` sections.",
        "",
    ]

    unresolved_status = [
        e for e in rows if e["meta"].get("status") in {"seed", "provisional", "contested"}
    ]
    lines += ["## Entries explicitly under development", ""]
    if unresolved_status:
        for entry in unresolved_status:
            meta = entry["meta"]
            lines.append(
                f"- **{meta['term']}** — {meta.get('status')}: {meta.get('gloss', '')}"
            )
    else:
        lines.append("_None currently marked seed, provisional, or contested._")
    lines.append("")

    lines += ["## Open questions by concept", ""]
    for entry in rows:
        questions = entry["open_questions"]
        if not questions:
            continue
        lines += [
            f"### {entry['meta']['term']}",
            "",
            questions,
            "",
            f"_Source: `{entry['path']}`_",
            "",
        ]

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_problem_pressure(entries: list[dict[str, Any]], output: Path) -> None:
    rows = sorted(entries, key=lambda e: str(e["meta"]["term"]).casefold())
    lines = [
        "# Conceptarium — Problem-Pressure Index",
        "",
        "> Reverse index from the frustration, anomaly, contradiction, or unfinished thought",
        "> that made a concept necessary. Generated from canonical `Problem pressure` sections.",
        "",
        "Use this projection when you remember **the problem** but have forgotten the word.",
        "",
    ]

    for entry in rows:
        pressure = entry["problem_pressure"]
        if not pressure:
            continue
        lines += [
            f"## {entry['meta']['term']}",
            "",
            pressure,
            "",
            f"_Canonical entry: `{entry['path']}`_",
            "",
        ]

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_catalog(entries: list[dict[str, Any]], output: Path) -> None:
    """Compact machine-readable index useful for blog/search/AI ingestion."""
    payload = []
    for entry in sorted(entries, key=lambda e: str(e["meta"]["id"])):
        meta = entry["meta"]
        payload.append(
            {
                "id": meta.get("id"),
                "term": meta.get("term"),
                "type": meta.get("type"),
                "status": meta.get("status"),
                "gloss": meta.get("gloss"),
                "domains": meta.get("domains") or [],
                "aliases": meta.get("aliases") or [],
                "origin": meta.get("origin") or {},
                "relations": meta.get("relations") or [],
                "source": entry["path"],
            }
        )
    output.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="directory for disposable generated projections",
    )
    args = parser.parse_args()

    entries = load_entries()
    output = args.output_dir
    output.mkdir(parents=True, exist_ok=True)

    write_dictionary(entries, output / "dictionary.md")
    write_graph(entries, output / "graph.json")
    write_frontier(entries, output / "frontier.md")
    write_problem_pressure(entries, output / "problem-pressure.md")
    write_catalog(entries, output / "catalog.json")

    print(
        f"Generated 5 projections from {len(entries)} canonical entries in {output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
