use crate::corpus::Corpus;
use anyhow::{Context, Result};
use serde_json::json;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

pub fn generate(corpus: &Corpus, output: &Path) -> Result<()> {
    fs::create_dir_all(output)
        .with_context(|| format!("creating {}", output.display()))?;

    write_dictionary(corpus, &output.join("dictionary.md"))?;
    write_graph(corpus, &output.join("graph.json"))?;
    write_frontier(corpus, &output.join("frontier.md"))?;
    write_problem_pressure(corpus, &output.join("problem-pressure.md"))?;
    write_promotion_queue(corpus, &output.join("promotion-queue.md"))?;
    write_registry(corpus, &output.join("registry.json"))?;
    write_catalog(corpus, &output.join("catalog.json"))?;

    let registry_only = corpus
        .registry
        .concepts
        .iter()
        .filter(|record| record.materialization == "registry-only")
        .count();

    println!(
        "Generated 7 projections from {} registered concepts ({} materialized, {} registry-only) in {}",
        corpus.registry.concepts.len(),
        corpus.entries.len(),
        registry_only,
        output.display()
    );
    Ok(())
}

fn write_dictionary(corpus: &Corpus, path: &Path) -> Result<()> {
    let mut entries = corpus.entries.iter().collect::<Vec<_>>();
    entries.sort_by_key(|entry| entry.meta.term.to_lowercase());

    let mut out = String::from(
        "# Conceptarium — Dictionary Projection\n\n> Generated from materialized canonical entries. Do not edit this file directly.\n\n",
    );

    for entry in entries {
        out.push_str(&format!("## {}\n\n{}\n\n", entry.meta.term, entry.meta.gloss));
        out.push_str(&format!(
            "**Type:** {}\n**Status:** {}\n",
            entry.meta.kind, entry.meta.status
        ));
        if !entry.meta.domains.is_empty() {
            out.push_str(&format!("**Domains:** {}\n", entry.meta.domains.join(", ")));
        }
        if !entry.meta.aliases.is_empty() {
            out.push_str(&format!("**Aliases:** {}\n", entry.meta.aliases.join(", ")));
        }
        out.push_str(&format!(
            "**Canonical source:** `{}`\n\n",
            entry.path.display()
        ));
    }

    fs::write(path, out).with_context(|| format!("writing {}", path.display()))
}

fn write_graph(corpus: &Corpus, path: &Path) -> Result<()> {
    let entries = corpus.entries_by_id();
    let registry = corpus.registry_by_id();

    let mut nodes = Vec::new();
    for record in &corpus.registry.concepts {
        if let Some(entry) = entries.get(record.id.as_str()) {
            nodes.push(json!({
                "id": record.id,
                "term": entry.meta.term,
                "materialization": "entry",
                "ontology_state": record.ontology_state,
                "type": entry.meta.kind,
                "status": entry.meta.status,
                "gloss": entry.meta.gloss,
                "domains": entry.meta.domains,
                "aliases": entry.meta.aliases,
                "origin": entry.meta.origin,
                "source": entry.path,
            }));
        } else {
            nodes.push(json!({
                "id": record.id,
                "term": record.term,
                "materialization": "registry-only",
                "ontology_state": record.ontology_state,
                "type": serde_json::Value::Null,
                "status": serde_json::Value::Null,
                "gloss": serde_json::Value::Null,
                "domains": [],
                "aliases": [],
                "origin": {},
                "source": serde_json::Value::Null,
                "queue_group": record.queue_group,
                "capture": record.capture,
            }));
        }
    }
    nodes.sort_by_key(|node| node["id"].as_str().unwrap_or_default().to_string());

    let mut edges = Vec::new();
    for entry in &corpus.entries {
        for relation in &entry.meta.relations {
            let target_record = registry.get(relation.target.as_str());
            edges.push(json!({
                "source": entry.meta.id,
                "type": relation.kind,
                "target": relation.target,
                "target_registered": target_record.is_some(),
                "target_materialization": target_record.map(|r| r.materialization.as_str()),
            }));
        }
    }
    edges.sort_by_key(|edge| {
        format!(
            "{}\u{0}{}\u{0}{}",
            edge["source"].as_str().unwrap_or_default(),
            edge["type"].as_str().unwrap_or_default(),
            edge["target"].as_str().unwrap_or_default()
        )
    });

    let payload = json!({
        "generated_from": ["registry/concepts.yml", "entries/*.md"],
        "registered_concept_count": nodes.len(),
        "materialized_entry_count": corpus.entries.len(),
        "edge_count": edges.len(),
        "nodes": nodes,
        "edges": edges,
    });

    write_json(path, &payload)
}

fn write_frontier(corpus: &Corpus, path: &Path) -> Result<()> {
    let mut queue = corpus
        .registry
        .concepts
        .iter()
        .filter(|record| record.materialization == "registry-only")
        .collect::<Vec<_>>();
    queue.sort_by_key(|record| record.term.to_lowercase());

    let mut out = String::from(
        "# Conceptarium — Research Frontier\n\n> Generated from registry presence, entry statuses, and `Open questions` sections.\n\n## Registered concepts awaiting materialization\n\n",
    );
    if queue.is_empty() {
        out.push_str("_No registry-only concepts._\n");
    } else {
        for record in queue {
            let suffix = record
                .queue_group
                .as_ref()
                .map(|group| format!(" — {group}"))
                .unwrap_or_default();
            out.push_str(&format!("- **{}** (`{}`){}\n", record.term, record.id, suffix));
        }
    }

    out.push_str("\n## Entries explicitly under development\n\n");
    let mut unresolved = corpus
        .entries
        .iter()
        .filter(|entry| matches!(entry.meta.status.as_str(), "seed" | "provisional" | "contested"))
        .collect::<Vec<_>>();
    unresolved.sort_by_key(|entry| entry.meta.term.to_lowercase());

    if unresolved.is_empty() {
        out.push_str("_None currently marked seed, provisional, or contested._\n");
    } else {
        for entry in unresolved {
            out.push_str(&format!(
                "- **{}** — {}: {}\n",
                entry.meta.term, entry.meta.status, entry.meta.gloss
            ));
        }
    }

    out.push_str("\n## Open questions by concept\n\n");
    let mut entries = corpus.entries.iter().collect::<Vec<_>>();
    entries.sort_by_key(|entry| entry.meta.term.to_lowercase());
    for entry in entries {
        if let Some(questions) = &entry.open_questions {
            out.push_str(&format!(
                "### {}\n\n{}\n\n_Source: `{}`_\n\n",
                entry.meta.term,
                questions,
                entry.path.display()
            ));
        }
    }

    fs::write(path, out).with_context(|| format!("writing {}", path.display()))
}

fn write_problem_pressure(corpus: &Corpus, path: &Path) -> Result<()> {
    let mut entries = corpus.entries.iter().collect::<Vec<_>>();
    entries.sort_by_key(|entry| entry.meta.term.to_lowercase());

    let mut out = String::from(
        "# Conceptarium — Problem-Pressure Index\n\n> Reverse index from the frustration, anomaly, contradiction, or unfinished thought\n> that made a concept necessary. Generated from canonical `Problem pressure` sections.\n\nUse this projection when you remember **the problem** but have forgotten the word.\n\n",
    );

    for entry in entries {
        if let Some(pressure) = &entry.problem_pressure {
            out.push_str(&format!(
                "## {}\n\n{}\n\n_Canonical entry: `{}`_\n\n",
                entry.meta.term,
                pressure,
                entry.path.display()
            ));
        }
    }

    fs::write(path, out).with_context(|| format!("writing {}", path.display()))
}

fn write_promotion_queue(corpus: &Corpus, path: &Path) -> Result<()> {
    let mut groups: BTreeMap<String, Vec<_>> = BTreeMap::new();
    for record in corpus
        .registry
        .concepts
        .iter()
        .filter(|record| record.materialization == "registry-only")
    {
        groups
            .entry(record.queue_group.clone().unwrap_or_else(|| "Ungrouped".to_string()))
            .or_default()
            .push(record);
    }

    let total = groups.values().map(Vec::len).sum::<usize>();
    let mut out = format!(
        "# Conceptarium — Promotion Queue\n\n> Generated from registry-only concepts in `registry/concepts.yml`.\n> Predicate presence is already durable; promotion means semantic materialization can happen later.\n\n**{total} registered concept(s) awaiting full materialization.**\n\n"
    );

    for (group, mut records) in groups {
        records.sort_by_key(|record| record.term.to_lowercase());
        out.push_str(&format!("## {group}\n\n"));
        for record in records {
            out.push_str(&format!(
                "### {}\n\n- **ID:** `{}`\n- **Ontology state:** {}\n",
                record.term, record.id, record.ontology_state
            ));
            if let Some(capture) = &record.capture {
                if let Some(note) = &capture.note {
                    out.push_str(&format!("- **Capture note:** {note}\n"));
                }
                if let Some(context) = &capture.context {
                    out.push_str(&format!("- **Context:** {context}\n"));
                }
            }
            out.push('\n');
        }
    }

    fs::write(path, out).with_context(|| format!("writing {}", path.display()))
}

fn write_registry(corpus: &Corpus, path: &Path) -> Result<()> {
    let mut records = corpus.registry.concepts.clone();
    records.sort_by_key(|record| record.id.clone());
    write_json(path, &records)
}

fn write_catalog(corpus: &Corpus, path: &Path) -> Result<()> {
    let entries = corpus.entries_by_id();
    let mut items = Vec::new();

    for record in &corpus.registry.concepts {
        if let Some(entry) = entries.get(record.id.as_str()) {
            items.push(json!({
                "id": entry.meta.id,
                "term": entry.meta.term,
                "presence": "registered",
                "materialization": "entry",
                "ontology_state": record.ontology_state,
                "type": entry.meta.kind,
                "status": entry.meta.status,
                "gloss": entry.meta.gloss,
                "domains": entry.meta.domains,
                "aliases": entry.meta.aliases,
                "origin": entry.meta.origin,
                "relations": entry.meta.relations,
                "source": entry.path,
            }));
        } else {
            items.push(json!({
                "id": record.id,
                "term": record.term,
                "presence": record.presence,
                "materialization": "registry-only",
                "ontology_state": record.ontology_state,
                "queue_group": record.queue_group,
                "capture": record.capture,
                "source": serde_json::Value::Null,
            }));
        }
    }
    items.sort_by_key(|item| item["id"].as_str().unwrap_or_default().to_string());
    write_json(path, &items)
}

fn write_json(path: &Path, value: &impl serde::Serialize) -> Result<()> {
    let mut text = serde_json::to_string_pretty(value)?;
    text.push('\n');
    fs::write(path, text).with_context(|| format!("writing {}", path.display()))
}

pub fn registry_only_relation_targets(corpus: &Corpus) -> BTreeSet<String> {
    let registered = corpus
        .registry
        .concepts
        .iter()
        .map(|record| record.id.as_str())
        .collect::<BTreeSet<_>>();
    let materialized = corpus
        .entries
        .iter()
        .map(|entry| entry.meta.id.as_str())
        .collect::<BTreeSet<_>>();

    corpus
        .entries
        .iter()
        .flat_map(|entry| &entry.meta.relations)
        .filter(|relation| {
            registered.contains(relation.target.as_str())
                && !materialized.contains(relation.target.as_str())
        })
        .map(|relation| relation.target.clone())
        .collect()
}
